# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    EnableIIS: true
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    WebsiteName: 'myTestApp'
    WebsitePhysicalPath: 'C:\Users\nishant\Desktop\publich'
    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b1203fbf-0853-42e0-b314-a904d487b23b)'
    command: 'build'
    projects: '.'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
