trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  publishFolder: '$(Build.ArtifactStagingDirectory)\publish'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: sdk
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output "$(publishFolder)"'
    zipAfterPublish: false

- powershell: |
    Write-Host "Stopping IIS Website..."
    Stop-WebSite -Name "myTestApp"

    Write-Host "Stopping App Pool..."
    Stop-WebAppPool -Name "myTestAppPool"
  displayName: 'Stop IIS'

- task: CopyFiles@2
  displayName: 'Deploy to IIS Folder'
  inputs:
    SourceFolder: '$(publishFolder)'
    Contents: '**'
    TargetFolder: 'C:\inetpub\myTestApp'
    CleanTargetFolder: true
    OverWrite: true

- powershell: |
    Write-Host "Starting App Pool..."
    Start-WebAppPool -Name "myTestAppPool"

    Write-Host "Starting Website..."
    Start-WebSite -Name "myTestApp"
  displayName: 'Start IIS'